### PR TITLE
HelpRequests Index Page

### PR DESCRIPTION
**Pull request by JonathanCheng123**
Added index page for HelpRequests, plus stories and testing.
Screenshot of new index page:

Screenshot 2023-11-09 at 10 08 22 PM

Storybook link:
https://ucsb-cs156-f23.github.io/team03-f23-7pm-2/prs/110/storybook

### CODE REVIEW

**Review by MuMuKow — APPROVED** [review]
LGTM

**Review by MuMuKow — CHANGES_REQUESTED** [review]
Please fix merge conflicts

**Comment by JonathanCheng123** [comment]
Sorry just fixed it again, and tests are currently running

**Review by MuMuKow — APPROVED** [review]
LGTM

**Pull request merged**
